### ISSUE TITLE
Timesheets - 10/28

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#13]
- It's easy to accidentally select the wrong show(s) and not know it when creating a new timesheet since there isn't any indication on the timesheet page.

- When updating the sheet, it automatically resets the rate to Teacher $30.

**Comment by endgamesimprov** [comment]
- Added a visual display at the bottom if there exists related items. However, I have no way at the moment to undo them or change them. I will eventually, but this is not a feature of the old system and a new feature which I am ignoring at the moment for the sake of switching over first.

- I forgot if I mentioned or not, but there is a unfortunate issue with "Rate" that just can't be converted until after the switch day. I checked the code and this seems to be set up correctly for when the change happens. But I also started a new "Milestone" grouping that will remind us of the things to do on the day we switch over.

**Comment by thekarinoelle** [comment]
The visual is great!

**Comment by endgamesimprov** [comment]
Just leaving open so I remember to do the second bullet point on the switch over day

**Comment by scottendgames** [comment]
This is now done because of the cutover. TImesheets and payroll now are visible.
