### ISSUE TITLE
List - 10/28

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#14]
Teachers list is showing all past teachers including current.

**Comment by endgamesimprov** [comment]
This was indicated in my original email. Once we make the conversion final, we will need to manually go thru everyone's assignments and manually set dates. We've never had this information in the past, so there are not valid defaults. If I set the old teachers to a random default end date, we won't hold ourselves to correct them when we switch over. So it is is a little bit of a poison pill on purpose.

**Comment by thekarinoelle** [comment]
got it.
