### ISSUE TITLE
Calendar - 10/28

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#15]
The event name overflows in the day cell causing the role and location information to be missed. It would be ideal if it wrapped around.

**Comment by endgamesimprov** [comment]
Nice UI catch. Corrected!

**Comment by thekarinoelle** [comment]
Hey, I'm still having this issue. 
![Screen Shot 2019-11-01 at 12 07 19 AM](https://user-images.githubusercontent.com/56705710/68008277-9c79aa80-fc3b-11e9-9c0f-1a93185cde8d.png)
