### ISSUE TITLE
Closing a Class - 10/28

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#16]
When I try to close out a class it doesn't seem to remove itself from the list. I checked closed on the Wed 101 that started on 9/18 and submitted it, but it's still showing up on the group dynamics list.

**Comment by endgamesimprov** [comment]
Seems to be working fine. Can you test again please?

**Comment by endgamesimprov** [comment]
Oh, also, are you talking about 'closing' a class definition or a offering?

**Comment by thekarinoelle** [comment]
individual offering. again, now it's working. but it didn't when I wrote this. The VERY first time I tried this I believe it had worked. but I tried it again whilst I was testing something else and the offering wasn't disappearing from the list on the classes page.
