### ISSUE TITLE
Role/Agenda Quirk - 10/31

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#19]
- If a role ends on the edit assignment page, but they were scheduled for an upcoming event, the schedule still shows up on their calendar/agenda page. (ie. assigned teacher to an offering, the role ends before the class does, offering shows up on agenda/calendar without permissions of the teacher).

- Not sure if this is something to fix, but wanted to bring attention in case this wasn't purposeful. I can see where this is beneficial in case there was an accident in the role assignment on my part. But could find the user to be quite confused by it.

**Comment by endgamesimprov** [comment]
Nope, this is by design. It might be a very very advance feature such as "Cannot remove assignment while person is assign". But the simplest way to move forward is just to know that they can be out of sync.
