### ISSUE TITLE
Producer's Permissions - 10/31

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#20]
Do non-employed producers need to see the shows page if they already have access to only their shows on the agenda and calendar page?

**Comment by scottendgames** [comment]
This is a good thought, but logically I think there are two positions in which they would need the Shows List page. 1. When a show is created for them, but we forge to assign them as producer. They can catch the mistake. 2. There is a very small hypothetical where they would not be the Producer of a specific day. But as mentioned, this is a very small use case. Most likely there would just be two Producers/
