### ISSUE TITLE
Make default gradshow pulldown option something other than the first item

### ISSUE THREAD

**Issue by scottendgames** [endgamesimprov/EgSites#24]
Set it to something blank and make sure it doesn't try to set a borked gradshow connection until set to a real value.

**Comment by thekarinoelle** [comment]
Can you elaborate on this? I'm not quite sure what this all means.

**Comment by scottendgames** [comment]
This is on a show page. At the top, is the pulldown menu to assign a graduation show. It always defaulted to the first item on the list. Max was concerned that someone would either a) accidentally hit "add gradshow" thereby doing something they did not want or b) assume the item displaying was the offering this show was tied to.

I now made it so the default option is "Select an Offering" and if someone tries to assign it, they get alerted to make a selection.

**Comment by thekarinoelle** [comment]
![Screen Shot 2019-11-13 at 5 23 06 PM](https://user-images.githubusercontent.com/56705710/68818620-6a544980-063a-11ea-9b18-66a87ad85da8.png)

this is what I'm seeing when i open up a show page and not select an offering.
