### ISSUE TITLE
Color coding Offerings based on date - Similar to former version

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#28]
When scheduling grad shows, it's a bit tougher to find the offerings that need to have grad shows scheduled now that the offerings are categorized by their parent. if we have the offerings coded, it would at least help me find which classes just kicked off. But other than that, I can't tell which ones already have grad shows unless I click through them.

**Comment by scottendgames** [comment]
Done. I luckily built this feature in and just forgot to enable the last step. Same colors as before.

I also caught another error once they were color coded. Past classes were being sorted towards the bottom. That has been fixed.
