### ISSUE TITLE
PayPal - Only enrolling one member at a time is allowed

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#29]
- Clicking "enroll" on multiple accounts will seem to enroll everyone as the confirmation pops up for all.
- Refreshing the page after clicking enroll on multiple accounts will undo all enrollments except for one.
- Only one enrollment is confirmed between refreshing the page regardless of how many you click to enroll.

**Comment by scottendgames** [comment]
Good catch. This was an issue where each enrollment was trying to use the same ID number for each one. ID numbers are meant to be unique, so if it runs into a duplicate, it just writes over the other one.

**Comment by thekarinoelle** [comment]
Reopening because I ran into the same issue.

- I can create multiple new accounts in one setting.
- Still running into only one account enrolling per refreshment of page.
