### ISSUE TITLE
Payroll Report - Person's Role/Rate repeats

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#32]
https://www.endgamesimprov.com/delclose/payroll.php?filter=personSummary&start=2019-10-26%20&end=2019-11-08

**Comment by scottendgames** [comment]
Corrected both on the UI for payroll and the CSV export. This had to do with the fact that timesheets underwent a backend column change. It was grouping by the old column, instead of the new one.
