### ISSUE TITLE
No Grad Show Indicator on Class List

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#33]
Previous offerings list would allow me to view whether a grad show has been assigned or not without having to click each offering. 

Having this option now would be VERY useful.

**Comment by scottendgames** [comment]
I added an indicator if any are set at least. It is a pretty poor indicator, but I can improve it once I figure out a consistent way to call up pop-up windows. 

But good catch, I never make this feature work.

**Comment by thekarinoelle** [comment]
![Screen Shot 2019-11-13 at 5 30 17 PM](https://user-images.githubusercontent.com/56705710/68818897-5ceb8f00-063b-11ea-8a6b-2e64839d8903.png)
![Screen Shot 2019-11-13 at 5 30 36 PM](https://user-images.githubusercontent.com/56705710/68818899-5eb55280-063b-11ea-868f-84eb86dd8836.png)

It doesn't seem like the indicator is working yet on the class list.
