### ISSUE TITLE
Clockout time off by an hour

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#37]
When I create a timesheet, the out time (which is supposed to be the current time, right?) is one hour ahead. I'm assuming this is a daylight savings issue?

**Comment by endgamesimprov** [comment]
Nope, the in-time is current time, he out time is +1 hour just to give it some separation

**Comment by thekarinoelle** [comment]
Is it only supposed to happen when creating a blank timesheet on the timesheet list page?
