### ISSUE TITLE
User Suggestion - Have Days listed before registrations

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#40]
On the Individual performance and offering pages, list the registrations last. 

Teachers will want to look for the attendance button associated with the date. I don't see any reason I need the list of people on top first. Plus, I'm constantly scrolling down to double-check the start date so I know which offering I'm on.

For performances, having the date listed before a long list of registrations will allow us to confirm the date is correct before looking into seeing who is registered for the show.

**Comment by endgamesimprov** [comment]
I like it. Done.
