### ISSUE TITLE
Offering Comment is Useful

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#41]
Being able to see specific notes about an offering when looking at the list, it's very useful to see notes related to event for scheduling purposes.

For example. I have a note about a Sunday offering having been postponed 3 times in a row. And, it's nice to easily see what kind of drop-in class is happening.

**Comment by endgamesimprov** [comment]
@Kuri-Sauce, I see the comments on the offering list. It is the little yellow note icon. Just hover your mouse. If this isn't what you were looking for, then please re-open and explain.

**Comment by thekarinoelle** [comment]
Sorry, this was unclear. I was making a note that I am finding them useful for this reason. You mentioned not knowing what to do with this feature and I find that using the comment section for this is good in my opinion.
