### ISSUE TITLE
PayPal Prereq only showing "exist" or "No req"

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#43]
this occurs even when someone has met the prereq.

**Comment by endgamesimprov** [comment]
You'll need to show me a specific example, I see plenty with "Met". Next time it appears, show me before proceeding.

**Comment by thekarinoelle** [comment]
this is what I'm seeing on adv and prod. Pham was the last purchase to show met before the switch.

![{9E1A1DA7-0ADB-4C64-926D-BE507CC1C4FF}](https://user-images.githubusercontent.com/56705710/68927950-cfdd2e80-073d-11ea-92a0-b9db5e8efda2.png)

**Comment by thekarinoelle** [comment]
![{6C1FC243-D0AA-4757-927E-A345309627F4}](https://user-images.githubusercontent.com/56705710/68928526-1da66680-073f-11ea-9d9b-61e077ca453f.png)

**Comment by scottendgames** [comment]
I cannot stress enough how stupid of a block of code this is. There are so many conditional statements going on here. I know it is working better, but not quite sure if it is perfect. Also, it seems like more records than Id expect are still not finding an "offering"s that match their Paypal at purchase time.
