### ISSUE TITLE
Past Attendance Checklist has issues determining responsible party

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#45]
![Screen Shot 2019-11-14 at 1 46 42 AM](https://user-images.githubusercontent.com/56705710/68846097-5a138d00-0681-11ea-9f7f-c6f8ea79a91f.png)
![Screen Shot 2019-11-14 at 1 46 11 AM](https://user-images.githubusercontent.com/56705710/68846098-5a138d00-0681-11ea-8c3b-9d3af8cdc2fa.png)
![Screen Shot 2019-11-14 at 1 46 52 AM](https://user-images.githubusercontent.com/56705710/68846099-5a138d00-0681-11ea-9f7d-0a884169b9f5.png)

**Comment by endgamesimprov** [comment]
FIxed, don't see anymore "Unable to Determine" at the moment. One thing that did occur to me is that teachers/coaches that are not there, need to mark themselves as absent or else they will still appear. This will get resolved when we have "Substitute" flags in a Registration and then better logic to identify if atleast one teacher for a given day is there.
