### ISSUE TITLE
Enhancement Request - Highlight start dates for new class cycles and workshops on calendar

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#49]
This is useful to make it easier to know when a new class cycle is starting to help me avoid missing details/postponing and increase my ability to do it quicker.

The new classes/offering layout is a bit tougher to see as a whole and I have to go through every dropdown to look at the individual offering of that level.

**Comment by scottendgames** [comment]
As usual, I try to avoid making something unique to one booking type (in this case, just offerings). So now the calendar will show a Greek Alpha symbol in parenthesis at the end of the name if it is the first one in a set of happenings. So this will also, for example, show up for a two day audition, or a two day teacher meeting. 

You can test in ADV. Also as is common, I'm not worrying about UI perfectly yet. But yes, I envision this being more UI friendly with a icon or color coding or pattern. But for now, the functionality is in and we can always do a UI prettying when we have more time and other important features are in.
