### ISSUE TITLE
Member page still displays "Public" after hiding it on assignment page

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#51]
![image](https://user-images.githubusercontent.com/56705710/69124370-8e5bc480-0a58-11ea-80d0-3f6441b411dc.png)

**Comment by thekarinoelle** [comment]
![image](https://user-images.githubusercontent.com/56705710/69124441-bea36300-0a58-11ea-924c-54962f246d83.png)

**Comment by scottendgames** [comment]
Great catch. Fixed!
