### ISSUE TITLE
Other Calendars list - Corinne isn't showing up on the list

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#53]
![Screen Shot 2019-11-20 at 2 04 40 PM](https://user-images.githubusercontent.com/56705710/69282276-c2410200-0b9e-11ea-8940-6d29ad90bbcc.png)

**Comment by scottendgames** [comment]
Corrected. In programming there are a lot of weird patterns when looping through data. I organize a list of all roles, sort by members, and there are duplicates. So to get rid of the duplicates you loop through the list and only print when your last name (previous loop) is different from the current name (new loop). Well, I forgot that for the first one I just need to print the name, else it is skipped.
