### ISSUE TITLE
attendance check in sheets are not alphabetically orgranized

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#65]
![Screen Shot 2019-12-05 at 4 42 29 PM](https://user-images.githubusercontent.com/56705710/70285988-4c33c200-177e-11ea-99cb-d8a02c51109d.png)

**Comment by endgamesimprov** [comment]
Sorting alphabetically now. Also caught another mistake that would show itself if Offering Days were created out of order. Also sorted the by name the Pass/Fail page.
