### ISSUE TITLE
Tue 401 Offering Page shows Code - Can't and Need to Access Registrations

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#73]
![Screen Shot 2019-12-27 at 11 01 27 AM](https://user-images.githubusercontent.com/56705710/71539741-b7903000-28f5-11ea-8477-4774bc91f1de.png)

**Comment by scottendgames** [comment]
Not sure what happened. But I think this resolved itself along with the other Zhu, Rong registration issue you saw. If you didn't do anything to try to fix it, my guess is that something in the database was temporarily locked up and it finally fixed itself. But let me know if this is not the case.
