### ISSUE TITLE
Zhu, Rong Student Registrations Lost

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#74]
![Screen Shot 2019-12-27 at 10 23 24 PM](https://user-images.githubusercontent.com/56705710/71539865-9af4f780-28f7-11ea-83ee-236af70b60ec.png)
![Screen Shot 2019-12-27 at 10 23 56 PM](https://user-images.githubusercontent.com/56705710/71539866-9b8d8e00-28f7-11ea-92ee-64559916f1e2.png)

After taking the above screenshots, I added their current enrollment and updated their email address. I took these steps and found an issue that could be the reason why their other enrollments are gone. 

- Clicked record on the PayPal page on their 401 purchase
- The Member was not set on the Individual registration even though I had enrolled them. The page showed the correct offering attendance dates. 
- I updated the Member to Zhu, Rong.
- Comments section contains the Paypal purchases address.

**Comment by thekarinoelle** [comment]
I checked a handful of other enrollment records on the PayPal page to see if the Member wasn't set, but couldn't find any.

**Comment by scottendgames** [comment]
Not sure what happened. But I think this resolved itself along with the other 401 page issue you saw. If you didn't do anything to try to fix it, my guess is that something in the database was temporarily locked up and it finally fixed itself. But let me know if this is not the case.

**Comment by thekarinoelle** [comment]
@scottendgames I can find their previous enrollments again. This time, I don't recall doing anything after you mentioned it being resolved. So, I'm not too sure of what may have caused it yet.
![Screen Shot 2020-01-18 at 12 32 03 AM](https://user-images.githubusercontent.com/56705710/72660983-1b07fd80-398a-11ea-90a6-492424af646c.png)
![Screen Shot 2020-01-18 at 12 33 39 AM](https://user-images.githubusercontent.com/56705710/72660993-34a94500-398a-11ea-914c-9d9a05a65a8a.png)

**Comment by scottendgames** [comment]
Just on a side note, if the issue isn't resolved, always "Reopen and Comment" else this can get lost.

To the issue! Is Rong associated with Helen Zhu? Because I oddly find a bunch of stranded registrations for a member_id number which in the history (not a perfect search) I only see connected to Helen Zhu.

**Comment by thekarinoelle** [comment]
Yup! That is the same person. But I wasn't able to find Helen on the member list.

**Comment by endgamesimprov** [comment]
Done
