### ISSUE TITLE
Access individual member pages from List page providing efficiency

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#83]
Being able to click on all the names on the list page to access their member page as an admin would be useful (students are less of a concern regarding this request). 

It would shortcut the step to go to the member page from viewing the list page, ctrl+F, type in their name, and click it from there. 

I find myself using the list page to search people by their role for various reasons (to view contact info as a whole, who is listed, is it up to date, etc) and then needing to access their member page to make changes or search for more info, etc.

**Comment by scottendgames** [comment]
Done. Please check behavior with permissions. As always now, you can do that in ADV (since it isn't currently broken)

**Comment by thekarinoelle** [comment]
looks great! thanks :)
