### ISSUE TITLE
Calendar- 10/24

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#9]
Missing 2989 - A

**Comment by scottendgames** [comment]
Need more info. I see something on 10/24 at 2989 - A.

**Comment by thekarinoelle** [comment]
2989 - A is showing up on the add/remove list now. when I posted this, it wasn't listed. not sure why.

**Comment by endgamesimprov** [comment]
Well, i know I was playing around with activating and deactivating it a few days ago. Don't remember when exactly, but maybe we overlapped or I left it inactive. Either way, I'll keep an eye out too.
